version: "3.1"

services:

  expert_system:
    container_name: expert_system
    image: expert_system
    volumes:
    - ./app:/app
    - ./package.json:/app/package.json
    - ./package-lock.json:/app/package-lock.json
    - /app/node_modules
    environment:
    - "NODE_ENV=dev"
    command: npm run dev
    ports:
    - 127.0.0.1:3000:3000
