version: 2
jobs:
    build:
        docker:
            - image: cypress/base:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: Linter
                command: npm run lint
            - run:
                name: Audit NPM
                command: npm audit
            - run:
                name: Start Server 
                command: npm start
                background: true
            - run:
                name: Sleep until server is up
                command: sleep 5
            - run:
                name: tests
                command: npm test
workflows:
    version: 2
    build-deploy:
        jobs:
            - build
